{"gradeable": true, "message": "Build was successful! 5 tests passed, 1 tests failed.", "score": 8, "output": "", "tests": [{"name": "test_move_out_of_turn", "points": 2, "max_points": 2, "message": "Success! Test [test_move_out_of_turn] passed."}, {"name": "test_o_winner", "points": 2, "max_points": 2, "message": "Success! Test [test_o_winner] passed."}, {"name": "test_x_goes_first", "points": 1, "max_points": 1, "message": "Success! Test [test_x_goes_first] passed."}, {"name": "test_play_after_win", "points": 1, "max_points": 1, "message": "Success! Test [test_play_after_win] passed."}, {"name": "test_play_on_same_square", "points": 2, "max_points": 2, "message": "Success! Test [test_play_on_same_square] passed."}, {"name": "test_get_winner", "points": 0, "max_points": 2, "message": "Test [test_get_winner] failed. See output below.", "output": "Valid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nValid Move\nthread 'test_get_winner' panicked at 'assertion failed: `(left == right)`\n  left: `None`,\n right: `Some(X)`', tests/test-tictactoe.rs:44:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"}]}